### ISSUE TITLE
Improve Code of Conduct

### ISSUE THREAD

**Issue by Anushka-shukla** [neil-dev/YouSafe#5]

**Comment by neil-dev** [comment]
Edit the code of conduct [here](https://github.com/neil-dev/YouSafe/blob/master/CODEOFCONDUCT.md).

**Comment by aniketrb-github** [comment]
@Anushka-shukla can I add more guidelines and some more details for contributors to adhere to?

**Comment by ayushi-1408** [comment]
Hey! I would love to do this issue. Please assign it to me.

**Comment by Anushka-shukla** [comment]
> @Anushka-shukla can I add more guidelines and some more details for contributors to adhere to?
> Can you please assign it to me? Thanks.

Hi @aniketrb-github Go ahead with it.

**Comment by Anushka-shukla** [comment]
> Hey! I would love to do this issue. Please assign it to me.

Hi @ayushi-1408 I like you enthusiasm, can you please work with the other issues raised as this one got assigned to @aniketrb-github .

**Comment by aniketrb-github** [comment]
just a question here,
Is it fine if I rename the file to make it more readable? to **CODE_OF_CONDUCT.md** from CODEOFCONDUCT.md
Can update the references present in the project as well along with it.

**Comment by Anushka-shukla** [comment]
@aniketrb-github Cool go ahead

**Comment by aniketrb-github** [comment]
one more, 
Should I exclude the **communication email** placeholder mentioned in the code of conduct file since currently, it does not have any email backed & hence navigates to a 404 page.
So should I keep it as is....or delete the placeholder of **communication email**?

**Comment by aniketrb-github** [comment]
@Anushka-shukla Can you please review my [P.R](https://github.com/neil-dev/YouSafe/pull/21) for this issue?
Thanks.
